# Form implementation generated from reading ui file 'lister.ui'
#
# Created by: PySide6 UI code generator 6.9.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PySide6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(981, 764)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.tabWidget = QtWidgets.QTabWidget(parent=self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Policy.Preferred,
            QtWidgets.QSizePolicy.Policy.Preferred,
        )
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tabWidget.sizePolicy().hasHeightForWidth())
        self.tabWidget.setSizePolicy(sizePolicy)
        self.tabWidget.setAutoFillBackground(True)
        self.tabWidget.setObjectName("tabWidget")
        self.fields_tab = QtWidgets.QWidget()
        self.fields_tab.setObjectName("fields_tab")
        self.gridLayout = QtWidgets.QGridLayout(self.fields_tab)
        self.gridLayout.setObjectName("gridLayout")
        self.fields_table = QtWidgets.QTableWidget(parent=self.fields_tab)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Policy.Preferred,
            QtWidgets.QSizePolicy.Policy.MinimumExpanding,
        )
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.fields_table.sizePolicy().hasHeightForWidth())
        self.fields_table.setSizePolicy(sizePolicy)
        self.fields_table.setContextMenuPolicy(
            QtCore.Qt.ContextMenuPolicy.ActionsContextMenu
        )
        self.fields_table.setSizeAdjustPolicy(
            QtWidgets.QAbstractScrollArea.SizeAdjustPolicy.AdjustIgnored
        )
        self.fields_table.setEditTriggers(
            QtWidgets.QAbstractItemView.EditTrigger.NoEditTriggers
        )
        self.fields_table.setSelectionMode(
            QtWidgets.QAbstractItemView.SelectionMode.NoSelection
        )
        self.fields_table.setShowGrid(True)
        self.fields_table.setGridStyle(QtCore.Qt.PenStyle.SolidLine)
        self.fields_table.setWordWrap(True)
        self.fields_table.setCornerButtonEnabled(False)
        self.fields_table.setRowCount(10)
        self.fields_table.setColumnCount(3)
        self.fields_table.setObjectName("fields_table")
        self.fields_table.horizontalHeader().setVisible(True)
        self.fields_table.horizontalHeader().setCascadingSectionResizes(False)
        self.fields_table.horizontalHeader().setHighlightSections(False)
        self.fields_table.horizontalHeader().setSortIndicatorShown(False)
        self.fields_table.horizontalHeader().setStretchLastSection(False)
        self.fields_table.verticalHeader().setVisible(False)
        self.fields_table.verticalHeader().setHighlightSections(False)
        self.gridLayout.addWidget(self.fields_table, 0, 0, 1, 1)
        self.tabWidget.addTab(self.fields_tab, "")
        self.teams_tab = QtWidgets.QWidget()
        self.teams_tab.setObjectName("teams_tab")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.teams_tab)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.teams_table = QtWidgets.QTableWidget(parent=self.teams_tab)
        self.teams_table.setRowCount(10)
        self.teams_table.setColumnCount(4)
        self.teams_table.setObjectName("teams_table")
        self.gridLayout_3.addWidget(self.teams_table, 0, 0, 1, 1)
        self.tabWidget.addTab(self.teams_tab, "")
        self.gridLayout_2.addWidget(self.tabWidget, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 981, 22))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(parent=self.menubar)
        self.menuFile.setObjectName("menuFile")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionOpen = QtGui.QAction(parent=MainWindow)
        self.actionOpen.setObjectName("actionOpen")
        self.actionSave = QtGui.QAction(parent=MainWindow)
        self.actionSave.setObjectName("actionSave")
        self.actionSave_as = QtGui.QAction(parent=MainWindow)
        self.actionSave_as.setObjectName("actionSave_as")
        self.actionExecute = QtGui.QAction(parent=MainWindow)
        self.actionExecute.setObjectName("actionExecute")
        self.menuFile.addAction(self.actionOpen)
        self.menuFile.addAction(self.actionSave)
        self.menuFile.addAction(self.actionSave_as)
        self.menuFile.addAction(self.actionExecute)
        self.menubar.addAction(self.menuFile.menuAction())

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.fields_table.setSortingEnabled(False)
        self.tabWidget.setTabText(
            self.tabWidget.indexOf(self.fields_tab), _translate("MainWindow", "Fields")
        )
        self.tabWidget.setTabText(
            self.tabWidget.indexOf(self.teams_tab), _translate("MainWindow", "Teams")
        )
        self.menuFile.setTitle(_translate("MainWindow", "Fichier"))
        self.actionOpen.setText(_translate("MainWindow", "Ouvrir"))
        self.actionSave.setText(_translate("MainWindow", "Enregistrer"))
        self.actionSave_as.setText(_translate("MainWindow", "Enregistrer sous..."))
        self.actionExecute.setText(_translate("MainWindow", "Exécuter"))
