# Form implementation generated from reading ui file 'periods.ui'
#
# Created by: PySide6 UI code generator 6.9.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PySide6 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(878, 588)
        self.gridLayout_3 = QtWidgets.QGridLayout(Dialog)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.splitter = QtWidgets.QSplitter(parent=Dialog)
        self.splitter.setOrientation(QtCore.Qt.Orientation.Vertical)
        self.splitter.setObjectName("splitter")
        self.treeWidget = QtWidgets.QTreeWidget(parent=self.splitter)
        self.treeWidget.setUniformRowHeights(True)
        self.treeWidget.setAnimated(False)
        self.treeWidget.setAllColumnsShowFocus(False)
        self.treeWidget.setObjectName("treeWidget")
        self.treeWidget.header().setVisible(True)
        self.treeWidget.header().setCascadingSectionResizes(False)
        self.treeWidget.header().setHighlightSections(False)
        self.treeWidget.header().setSortIndicatorShown(False)
        self.treeWidget.header().setStretchLastSection(False)
        self.days = QtWidgets.QFrame(parent=self.splitter)
        self.days.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.days.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.days.setObjectName("days")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.days)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.mon = QtWidgets.QCheckBox(parent=self.days)
        self.mon.setObjectName("mon")
        self.horizontalLayout_2.addWidget(self.mon)
        self.tue = QtWidgets.QCheckBox(parent=self.days)
        self.tue.setObjectName("tue")
        self.horizontalLayout_2.addWidget(self.tue)
        self.wed = QtWidgets.QCheckBox(parent=self.days)
        self.wed.setObjectName("wed")
        self.horizontalLayout_2.addWidget(self.wed)
        self.thu = QtWidgets.QCheckBox(parent=self.days)
        self.thu.setObjectName("thu")
        self.horizontalLayout_2.addWidget(self.thu)
        self.fri = QtWidgets.QCheckBox(parent=self.days)
        self.fri.setObjectName("fri")
        self.horizontalLayout_2.addWidget(self.fri)
        self.sat = QtWidgets.QCheckBox(parent=self.days)
        self.sat.setObjectName("sat")
        self.horizontalLayout_2.addWidget(self.sat)
        self.sun = QtWidgets.QCheckBox(parent=self.days)
        self.sun.setObjectName("sun")
        self.horizontalLayout_2.addWidget(self.sun)
        self.gridLayout_2.addLayout(self.horizontalLayout_2, 0, 0, 1, 1)
        self.frame = QtWidgets.QFrame(parent=self.splitter)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Policy.Expanding,
            QtWidgets.QSizePolicy.Policy.Expanding,
        )
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame.sizePolicy().hasHeightForWidth())
        self.frame.setSizePolicy(sizePolicy)
        self.frame.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.frame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame.setObjectName("frame")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.frame)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.selection_splitter = QtWidgets.QSplitter(parent=self.frame)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Policy.Expanding,
            QtWidgets.QSizePolicy.Policy.Expanding,
        )
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(
            self.selection_splitter.sizePolicy().hasHeightForWidth()
        )
        self.selection_splitter.setSizePolicy(sizePolicy)
        self.selection_splitter.setOrientation(QtCore.Qt.Orientation.Horizontal)
        self.selection_splitter.setObjectName("selection_splitter")
        self.entries = QtWidgets.QFrame(parent=self.selection_splitter)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Policy.Expanding,
            QtWidgets.QSizePolicy.Policy.Expanding,
        )
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.entries.sizePolicy().hasHeightForWidth())
        self.entries.setSizePolicy(sizePolicy)
        self.entries.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.entries.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.entries.setObjectName("entries")
        self.gridLayout = QtWidgets.QGridLayout(self.entries)
        self.gridLayout.setObjectName("gridLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.start = QtWidgets.QSpinBox(parent=self.entries)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Policy.Expanding,
            QtWidgets.QSizePolicy.Policy.Expanding,
        )
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.start.sizePolicy().hasHeightForWidth())
        self.start.setSizePolicy(sizePolicy)
        self.start.setMaximum(24)
        self.start.setObjectName("start")
        self.horizontalLayout.addWidget(self.start)
        self.end = QtWidgets.QSpinBox(parent=self.entries)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Policy.Expanding,
            QtWidgets.QSizePolicy.Policy.Expanding,
        )
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.end.sizePolicy().hasHeightForWidth())
        self.end.setSizePolicy(sizePolicy)
        self.end.setMaximum(24)
        self.end.setObjectName("end")
        self.horizontalLayout.addWidget(self.end)
        self.type_combo = QtWidgets.QComboBox(parent=self.entries)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Policy.Expanding,
            QtWidgets.QSizePolicy.Policy.Expanding,
        )
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.type_combo.sizePolicy().hasHeightForWidth())
        self.type_combo.setSizePolicy(sizePolicy)
        self.type_combo.setModelColumn(0)
        self.type_combo.setObjectName("type_combo")
        self.type_combo.addItem("")
        self.type_combo.addItem("")
        self.horizontalLayout.addWidget(self.type_combo)
        self.gridLayout.addLayout(self.horizontalLayout, 0, 0, 1, 1)
        self.frame_3 = QtWidgets.QFrame(parent=self.selection_splitter)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Policy.Expanding,
            QtWidgets.QSizePolicy.Policy.Expanding,
        )
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_3.sizePolicy().hasHeightForWidth())
        self.frame_3.setSizePolicy(sizePolicy)
        self.frame_3.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_3.setLineWidth(1)
        self.frame_3.setObjectName("frame_3")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.frame_3)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.add = QtWidgets.QPushButton(parent=self.frame_3)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Policy.Expanding,
            QtWidgets.QSizePolicy.Policy.Expanding,
        )
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.add.sizePolicy().hasHeightForWidth())
        self.add.setSizePolicy(sizePolicy)
        self.add.setObjectName("add")
        self.horizontalLayout_3.addWidget(self.add)
        self.del_but = QtWidgets.QPushButton(parent=self.frame_3)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Policy.Expanding,
            QtWidgets.QSizePolicy.Policy.Expanding,
        )
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.del_but.sizePolicy().hasHeightForWidth())
        self.del_but.setSizePolicy(sizePolicy)
        self.del_but.setObjectName("del")
        self.horizontalLayout_3.addWidget(self.del_but)
        self.gridLayout_4.addLayout(self.horizontalLayout_3, 0, 0, 1, 1)
        self.horizontalLayout_4.addWidget(self.selection_splitter)
        self.gridLayout_3.addWidget(self.splitter, 0, 0, 1, 1)
        self.buttonBox = QtWidgets.QDialogButtonBox(parent=Dialog)
        self.buttonBox.setOrientation(QtCore.Qt.Orientation.Horizontal)
        self.buttonBox.setStandardButtons(
            QtWidgets.QDialogButtonBox.StandardButton.Cancel
            | QtWidgets.QDialogButtonBox.StandardButton.Ok
        )
        self.buttonBox.setObjectName("buttonBox")
        self.gridLayout_3.addWidget(self.buttonBox, 1, 0, 1, 1)

        self.retranslateUi(Dialog)
        self.type_combo.setCurrentIndex(0)
        self.buttonBox.accepted.connect(Dialog.accept)  # type: ignore
        self.buttonBox.rejected.connect(Dialog.reject)  # type: ignore
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.treeWidget.setSortingEnabled(False)
        self.mon.setText(_translate("Dialog", "Lundi"))
        self.tue.setText(_translate("Dialog", "Mardi"))
        self.wed.setText(_translate("Dialog", "Mercredi"))
        self.thu.setText(_translate("Dialog", "Jeudi"))
        self.fri.setText(_translate("Dialog", "Vendredi"))
        self.sat.setText(_translate("Dialog", "Samedi"))
        self.sun.setText(_translate("Dialog", "Dimanche"))
        self.type_combo.setItemText(0, _translate("Dialog", "Naturel"))
        self.type_combo.setItemText(1, _translate("Dialog", "Synthétique"))
        self.add.setText(_translate("Dialog", "Ajouter"))
        self.del_but.setText(_translate("Dialog", "Supprimer"))
